### ISSUE TITLE
Pushboxes can overlap / offset issue

### ISSUE THREAD

**Issue by ViviMayoi** [ViviMayoi/fbneo-training-asurabus#9]
Pushboxes can actually overlap, as opposed to what their very role should be. There is missing logic to properly align them to match the game's behavior

**Comment by Xenn765** [comment]
Should be fixed in [b600427b389d11e799411433d23d2c4761ec51eb](https://github.com/ViviMayoi/fbneo-training-asurabus/commit/b600427b389d11e799411433d23d2c4761ec51eb)

**Comment by ViviMayoi** [comment]
> Should be fixed in [b600427b389d11e799411433d23d2c4761ec51eb](https://github.com/ViviMayoi/fbneo-training-asurabus/commit/b600427b389d11e799411433d23d2c4761ec51eb)

Closed!
